// Generated by CoffeeScript 1.11.1
(function() {
  var app, dependencies;

  dependencies = ['ngRoute', 'ngCookies', 'ui.calendar', 'ui.bootstrap', 'ui.select', 'ngSanitize', 'mpApp.filters', 'mpApp.directives', 'mpApp.routeConfig', 'mpApp.services', 'mpApp.controllers'];

  app = angular.module('mpApp', dependencies);

  angular.module('mpApp.routeConfig', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'pages/venueProfile.html'
      }).when('/register', {
        templateUrl: 'pages/createUser.html'
      }).when('/dashboard', {
        templateUrl: 'pages/dashboard.html'
      }).when('/event/:eventName', {
        templateUrl: 'pages/event.html'
      }).when('/newevent', {
        templateUrl: 'pages/venueProfile.html'
      }).when('/b2bwellcome', {
        templateUrl: 'pages/businessWellcome.html'
      }).when('/b2bcreate', {
        templateUrl: 'pages/createBusinessUser.html'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]).config([
    '$locationProvider', function($locationProvider) {
      return $locationProvider.html5Mode({
        enabled: true,
        requireBase: false
      });
    }
  ]);

  this.controllersModule = angular.module('mpApp.controllers', []);

  this.servicesModule = angular.module('mpApp.services', []);

  this.directivesModule = angular.module('mpApp.directives', []);

  this.filtersModule = angular.module('mpApp.filters', []);

}).call(this);
