// Generated by CoffeeScript 1.11.1
(function() {
  var AuthCtrl;

  AuthCtrl = (function() {
    function AuthCtrl($cookieStore, $log, $location, UserService) {
      this.$cookieStore = $cookieStore;
      this.$log = $log;
      this.$location = $location;
      this.UserService = UserService;
      this.$log.debug("Cookies Controlles created");
    }

    AuthCtrl.prototype.logoff = function() {
      this.$log.debug("logoff");
      this.$location.path("/");
      this.$cookieStore.remove('userdata');
      return this.UserService.auth(void 0);
    };

    AuthCtrl.prototype.isActive = function() {
      return !angular.isUndefined(this.UserService.user);
    };

    return AuthCtrl;

  })();

  controllersModule.controller('AuthCtrl', ['$cookieStore', '$log', '$location', 'UserService', AuthCtrl]);

}).call(this);
