// Generated by CoffeeScript 1.11.1
(function() {
  var CalendarService;

  CalendarService = (function() {
    function CalendarService($compile, $timeout, uiCalendarConfig, $log) {
      this.$compile = $compile;
      this.$timeout = $timeout;
      this.uiCalendarConfig = uiCalendarConfig;
      this.$log = $log;
      this.$log.debug("CalendarService created");
      this.eventClicked = {};
      this.uiConfig = {
        calendar: {
          height: 'auto',
          firstDay: 1,
          editable: true,
          header: {
            left: 'title',
            center: '',
            right: 'today prev,next'
          },
          eventClick: this.onEventClick,
          eventRender: this.eventRender
        }
      };
    }

    CalendarService.prototype.onEventClick = function(date, jsEvent, view) {
      this.eventClicked = date;
      console.log("Event clicked --> " + date.url + " , " + date.title + ", " + this.eventClicked.title);
      if (typeof date.url === 'undefined') {
        $('#myModal').modal('toggle');
        $('#myModalLabel').text(date.title);
        $('#myModalInfo').text(date.info);
        $('#modalWhen').text(moment(date.start).format("DD-MM-YYYY"));
        $('#modalPeopleCount').text(33);
        return $('#modalCommentsCount').text(12);
      } else {
        return console.log("open link");
      }
    };

    CalendarService.prototype.eventRender = function(event, element, view) {
      return console.log("ev render");
    };

    CalendarService.prototype.renderCalender = function(calendar) {
      if (this.uiCalendarConfig.calendars[calendar]) {
        return this.uiCalendarConfig.calendars[calendar].fullCalendar('render');
      }
    };

    return CalendarService;

  })();

  servicesModule.service('CalendarService', ['$compile', '$timeout', 'uiCalendarConfig', '$log', CalendarService]);

}).call(this);
