// Generated by CoffeeScript 1.11.1
(function() {
  var vomit;

  $(function() {
    $("#sres").hide;
    console.log("Document is ready..." + vomit);
    return $("#sin").click(function() {
      return console.log("sin clicked");
    });
  });

  vomit = function() {
    return console.log("is vomitting blaaa ~~~");
  };

}).call(this);
