// Generated by CoffeeScript 1.11.1
(function() {
  var B2BUserCtrl;

  B2BUserCtrl = (function() {
    function B2BUserCtrl($cookieStore, $log, $location, $document, UserService) {
      this.$cookieStore = $cookieStore;
      this.$log = $log;
      this.$location = $location;
      this.$document = $document;
      this.UserService = UserService;
      this.$log.debug("B2B UserCtrl created");
      this.loadMap();
      this.initGallery();
    }

    B2BUserCtrl.prototype.loadMap = function() {
      var mapLeaflet;
      this.$log.debug("Load Map data");
      L.mapbox.accessToken = 'pk.eyJ1Ijoia296bG93c3QiLCJhIjoiY2lzeGVlNTFnMDAyeTJ0cGR2N3czaXN3ciJ9.fmbuFc5B24xKGiiLJ7mrpA';
      mapLeaflet = L.mapbox.map('map', 'mapbox.streets', {
        scrollWheelZoom: false
      }).setView([38.913184, -77.031952], 16);
      return L.marker([38.913184, -77.031952]).addTo(mapLeaflet);
    };

    B2BUserCtrl.prototype.initGallery = function() {
      this.$log.debug("init gallery");
      return this.$document.find('#gallery').poptrox({
        baseZIndex: 20000,
        fadeSpeed: 300,
        overlayOpacity: 0,
        popupCloserText: '',
        popupHeight: 150,
        popupLoaderText: '',
        popupSpeed: 300,
        popupWidth: 150,
        usePopupCaption: true,
        usePopupCloser: true,
        usePopupDefaultStyling: true,
        usePopupForceClose: true,
        usePopupLoader: true,
        usePopupNav: true,
        windowMargin: 50
      });
    };

    return B2BUserCtrl;

  })();

  controllersModule.controller('B2BUserCtrl', ['$cookieStore', '$log', '$location', '$document', 'UserService', B2BUserCtrl]);

}).call(this);
