// Generated by CoffeeScript 1.11.1
(function() {
  var CreateUserCtrl;

  CreateUserCtrl = (function() {
    function CreateUserCtrl($log, $location, UserService) {
      this.$log = $log;
      this.$location = $location;
      this.UserService = UserService;
      this.$log.debug("User ctrl created");
      this.interests = ["UX", "meetups"];
      this.skills = [];
      this.picSource = "/assets/images/GreyPeople.png";
    }

    CreateUserCtrl.prototype.createUser = function() {
      var i, j, len, len1, obj, ref, ref1, results;
      this.$log.debug("User creation request triggered: " + this.user.name);
      ref = this.skills;
      for (i = 0, len = ref.length; i < len; i++) {
        obj = ref[i];
        this.$log.debug("skill: " + JSON.stringify(obj));
      }
      ref1 = this.interests;
      results = [];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        obj = ref1[j];
        results.push(this.$log.debug("tag: " + JSON.stringify(obj)));
      }
      return results;
    };

    CreateUserCtrl.prototype.uploadPicture = function() {
      return this.$log.debug("upload Picture");
    };

    return CreateUserCtrl;

  })();

  controllersModule.controller('CreateUserCtrl', ['$log', '$location', 'UserService', CreateUserCtrl]);

}).call(this);
