// Generated by CoffeeScript 1.11.1
(function() {
  var SigninUserCtrl;

  SigninUserCtrl = (function() {
    function SigninUserCtrl($cookieStore, $log, $location, $http, UserService) {
      this.$cookieStore = $cookieStore;
      this.$log = $log;
      this.$location = $location;
      this.$http = $http;
      this.UserService = UserService;
      this.$log.debug("SigninUserCtrl created");
      this.userprofile = this.$cookieStore.get('userdata');
      if (!this.isUndefined(this.userprofile)) {
        this.$log.debug("User is remembered, redirect to dashboard");
        this.$location.path("/dashboard");
      }
    }

    SigninUserCtrl.prototype.loginUser = function() {
      return this.UserService.signin(this.user).then((function(_this) {
        return function(data) {
          _this.$log.debug("LOGIN " + data.data.user.firstName + ", " + data.data.status);
          if (data.data.status === 0) {
            _this.$log.debug("Logged IN OK!");
            _this.userprofile = data.data.user;
            _this.$cookieStore.put('userdata', data.data.user);
            _this.$location.path("/dashboard");
            return _this.UserService.auth(data.data.user);
          } else {
            _this.$log.debug("Login failed " + data.data.status);
            return _this.$location.path("/");
          }
        };
      })(this));
    };

    SigninUserCtrl.prototype.createUser = function() {
      this.$log.debug("createUser()");
      this.user.active = true;
      return this.UserService.createUser(this.user).then((function(_this) {
        return function(data) {
          _this.$log.debug("Promise returned " + data + " User");
          _this.user = data;
          return _this.$location.path("/");
        };
      })(this), (function(_this) {
        return function(error) {
          return _this.$log.error("Unable to create User: " + error);
        };
      })(this));
    };

    SigninUserCtrl.prototype.isUndefined = function(value) {
      return angular.isUndefined(value) || value === null;
    };

    return SigninUserCtrl;

  })();

  controllersModule.controller('SigninUserCtrl', ['$cookieStore', '$log', '$location', '$http', 'UserService', SigninUserCtrl]);

}).call(this);
